<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Base\TituloEducativo;

class TituloEducativoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        TituloEducativo::truncate();

        $data = [
            "Actividad física" => "Actividad física",
"Agricultura de precisión" => "Agricultura de precisión",
"Agrobiotecnología" => "Agrobiotecnología",
"Agroindustria alimentaria" => "Agroindustria alimentaria",
"Agroindustria panelera" => "Agroindustria panelera",
"Agua y saneamiento" => "Agua y saneamiento",
"Alistamiento de laboratorios de análisis y ensayos para la industria" => "Alistamiento de laboratorios de análisis y ensayos para la industria",
"Almacenamiento, empaque y embalaje de objetos" => "Almacenamiento, empaque y embalaje de objetos",
"Analisis y desarrollo de sistemas de información" => "Analisis y desarrollo de sistemas de información",
"Animación digital" => "Animación digital",
"Analisis de materiales para la industria" => "Analisis de materiales para la industria",
"Analisis de muestras quimicas" => "Analisis de muestras quimicas",
"Apoyo administrativo en salud" => "Apoyo administrativo en salud",
"Apoyo logistico en eventos y servicios empresariales" => "Apoyo logistico en eventos y servicios empresariales",
"Aprovechamiento y beneficio del cultivo del caucho natural" => "Aprovechamiento y beneficio del cultivo del caucho natural",
"Artesanias tradicionales en tejido de punto " => "Artesanias tradicionales en tejido de punto ",
"Aseguramiento de la calidad del café en la finca" => "Aseguramiento de la calidad del café en la finca",
"Aseguramiento metrológico industrial" => "Aseguramiento metrológico industrial",
"Asesoría comercial" => "Asesoría comercial",
"Asesoría comercial y operaciones de entidades financieras" => "Asesoría comercial y operaciones de entidades financieras",
"Asistencia administrativa" => "Asistencia administrativa",
"Ejecución de programas deportivos" => "Ejecución de programas deportivos",
"Ejecución musical con instrumentos funcionales" => "Ejecución musical con instrumentos funcionales",
"El riesgo crediticio y su administración" => "El riesgo crediticio y su administración",
"Elaboración de prendas de vestir sobre medidas" => "Elaboración de prendas de vestir sobre medidas",
"Elaboración de productos de confiteria" => "Elaboración de productos de confiteria",
"Asistencia en organización de archivos" => "Asistencia en organización de archivos",
"Agroindustria alimentaria al paciente domiciliario" => "Agroindustria alimentaria al paciente domiciliario",
"Atención prehospitalaria" => "Atención prehospitalaria",
"Automatización industrial" => "Automatización industrial",
"Bilingual expert on business process outsourcing" => "Bilingual expert on business process outsourcing",
"Carpinteria" => "Carpinteria",
"Carpinteria metálica" => "Carpinteria metálica",
"Carpintero instalador" => "Carpintero instalador",
"Carpinteria de aluminio" => "Carpinteria de aluminio",
"Catastro" => "Catastro",
"Cocina" => "Cocina",
"Comercialización de alimentos" => "Comercialización de alimentos",
"Comercialización de productos masivos" => "Comercialización de productos masivos",
"Comercio internacional" => "Comercio internacional",
"Compras y suministros" => "Compras y suministros",
"Comunicación comercial" => "Comunicación comercial",
"Confección industrial" => "Confección industrial",
"Confección industrial de ropa deportiva" => "Confección industrial de ropa deportiva",
"Confección industrial de ropa exterior" => "Confección industrial de ropa exterior",
"Construcción y montaje de instalaciones eléctricas" => "Construcción y montaje de instalaciones eléctricas",
"Construcción en madera" => "Construcción en madera",
"Construcciones livianas en seco" => "Construcciones livianas en seco",
"Contabilidad y finanzas" => "Contabilidad y finanzas",
"Elaboración de audiovisuales" => "Elaboración de audiovisuales",
"Elaboración de objetos artesanales con semillas y maderables" => "Elaboración de objetos artesanales con semillas y maderables",
"Contabilización de operaciones comerciales y financieras" => "Contabilización de operaciones comerciales y financieras",
"Control de calidad de alimentos" => "Control de calidad de alimentos",
"Control de calidad en confecciones comerciales y financieras" => "Control de calidad en confecciones comerciales y financieras",
"Control de calidad en confección" => "Control de calidad en confección",
"Corte y venta de carnes" => "Corte y venta de carnes",
"Cosmetología y esttica de manos y pies" => "Cosmetología y esttica de manos y pies",
"Cuidado estetico de manos  y pies" => "Cuidado estetico de manos  y pies",
"Cultivo y cosecha de palma de aceite" => "Cultivo y cosecha de palma de aceite",
"Cultivos agrícolas" => "Cultivos agrícolas",
"Decoración de espacios interiores" => "Decoración de espacios interiores",
"Desarrollo de aplicaciones para dispositivos móviles" => "Desarrollo de aplicaciones para dispositivos móviles",
"Desarrollo de operaciones lógisicas en la cadena de abastecimiento" => "Desarrollo de operaciones lógisicas en la cadena de abastecimiento",
"Diagnostico y analisis organizacional para unidades productivas" => "Diagnostico y analisis organizacional para unidades productivas",
"Dibujo mecanico" => "Dibujo mecanico",
"Dirección de ventas" => "Dirección de ventas",
"Diseño de componentes de calzado" => "Diseño de componentes de calzado",
"Diseño de elemenos mecanicos para su fabricacion con maquinas herramientas" => "Diseño de elemenos mecanicos para su fabricacion con maquinas herramientas",
"Diseño de investigaciones de mercadeo" => "Diseño de investigaciones de mercadeo",
"Ebanisteria" => "Ebanisteria",
"Ejecución de clases grupales orientada al fitness" => "Ejecución de clases grupales orientada al fitness",
"Ejecución de eventos deportivos y recreativos" => "Ejecución de eventos deportivos y recreativos",
"Ejecución de la danza" => "Ejecución de la danza",
"Diseño e integracion de multimedia" => "Diseño e integracion de multimedia",
"Ebanistería y carpintería " => "Ebanistería y carpintería ",
"Redes electricas residenciales e industriales" => "Redes electricas residenciales e industriales",
"Reparación de equipos electrónicos de potencia" => "Reparación de equipos electrónicos de potencia",
"Mecanica automotriz" => "Mecanica automotriz",
"Mecanica industrial" => "Mecanica industrial",
"Soldadura" => "Soldadura",
"Auxiliar de publicaciones graficas" => "Auxiliar de publicaciones graficas",
"Soporte y mantenimiento de tecnologías de la información" => "Soporte y mantenimiento de tecnologías de la información",
"Curso en reparación de motocicletas" => "Curso en reparación de motocicletas",
"Tecnologia en Gastronomia y arte culinario" => "Tecnologia en Gastronomia y arte culinario",
"Tecnologia en Comercio Exterior y Negocios internacionales" => "Tecnologia en Comercio Exterior y Negocios internacionales",
"Tecnologia en Desarrollo de Software y aplicativos" => "Tecnologia en Desarrollo de Software y aplicativos",
"Tecnologia en Mercadeo y estrategias comerciales" => "Tecnologia en Mercadeo y estrategias comerciales",
"Tecnologia en Gestion de la Seguridad y Salud en el trabajo" => "Tecnologia en Gestion de la Seguridad y Salud en el trabajo",
"Tecnologia en Gestión de Empresas Turisticas y Hoteleras" => "Tecnologia en Gestión de Empresas Turisticas y Hoteleras",
"Tecnologia en Gestión administrativa" => "Tecnologia en Gestión administrativa",
"Tecnologia en gestión logistica internacional" => "Tecnologia en gestión logistica internacional",
"Tecnología en Moda e indumentaria " => "Tecnología en Moda e indumentaria ",
"Tecnico profesional en maquillaje artistico" => "Tecnico profesional en maquillaje artistico",
"Tecnologia en Gestión de la Moda" => "Tecnologia en Gestión de la Moda",
"Tecnologia en produccion grafica digital" => "Tecnologia en produccion grafica digital",
"Tecnologia en produccion fotografia" => "Tecnologia en produccion fotografia",
"Tecnologia en produccion escenica y visual" => "Tecnologia en produccion escenica y visual",
"Tecnologia en interiorismo sostenible" => "Tecnologia en interiorismo sostenible",
"Tecnico profesional en pasteleria y panaderia" => "Tecnico profesional en pasteleria y panaderia",
"Tecnologia en producción gastronomica" => "Tecnologia en producción gastronomica",
"Tecnologo en Gestión de industrias creativas" => "Tecnologo en Gestión de industrias creativas",
"Tecnico profesional en producción agropecuaria" => "Tecnico profesional en producción agropecuaria",
"Tecnologia en gestión sostenible de la producción agropecuaria" => "Tecnologia en gestión sostenible de la producción agropecuaria",
"Cocina" => "Cocina",
"Auxiliar de cocina" => "Auxiliar de cocina",
"Panaderia" => "Panaderia",
"Pasteleria" => "Pasteleria",
"Pasteleria y panaderia" => "Pasteleria y panaderia",
"Bartender" => "Bartender",
"Sommelier" => "Sommelier",
"Barismo" => "Barismo",
"Servicio de alimentos y eventos" => "Servicio de alimentos y eventos",
"Servicio de eventos" => "Servicio de eventos",
"Comercio y negocios internacionales" => "Comercio y negocios internacionales",
"Administración de empresas" => "Administración de empresas",
"Seguridad y salud en el trabajo" => "Seguridad y salud en el trabajo",
"Turismo y gastronomía" => "Turismo y gastronomía",
"Administración del talento humano" => "Administración del talento humano",
"Gestión turística y hotelera" => "Gestión turística y hotelera",
"Fotografía" => "Fotografía",
"Computación y desarrollo de software" => "Computación y desarrollo de software",
"Administración de sistemas de información y documentación" => "Administración de sistemas de información y documentación",
"Asistente administrativo" => "Asistente administrativo",
"Cuidado de niños" => "Cuidado de niños",
"Idioma extranjero" => "Idioma extranjero",
"Secretariado gerencial" => "Secretariado gerencial",
"Sistemas" => "Sistemas",
"Gestión de servicios financieros" => "Gestión de servicios financieros",
"Gstión del Talento y Recursos Humanos" => "Gstión del Talento y Recursos Humanos",
"Competencias en Hoteleria y Turismo" => "Competencias en Hoteleria y Turismo",
"Producción agropecuaria" => "Producción agropecuaria",
"Auxiliar administrativo" => "Auxiliar administrativo",
"Auxiliar contable y financiero" => "Auxiliar contable y financiero",
"Auxiliar en recursos humanos" => "Auxiliar en recursos humanos",
"Atención y educación integral a la primera infancia" => "Atención y educación integral a la primera infancia",
"Cocina nacional e internacional " => "Cocina nacional e internacional ",
"Seguridad ocupacional" => "Seguridad ocupacional",
"Diseño de modas" => "Diseño de modas",
"Auxiliar en comunicación grafica y publicitaria" => "Auxiliar en comunicación grafica y publicitaria",
"Auxiliar en clinica veterinaria y cuidado de mascotas" => "Auxiliar en clinica veterinaria y cuidado de mascotas",
"Auxiliar en enfermería" => "Auxiliar en enfermería",
"Servicio farmaceutico " => "Servicio farmaceutico ",
"Auxiliar en enfermeria" => "Auxiliar en enfermeria",
"Cosmetología y estetica integral" => "Cosmetología y estetica integral",
"Arte culinario" => "Arte culinario",
"Pasteleria y arte dulce" => "Pasteleria y arte dulce",
"Servicio de alimentos y bebidas" => "Servicio de alimentos y bebidas",
"Operación de servicios hoteleros " => "Operación de servicios hoteleros ",
"Operación de eventos " => "Operación de eventos ",
"Auxiliar en seguridad y salud en el trabajo" => "Auxiliar en seguridad y salud en el trabajo",
"Auxiliar en servicios farmaceuticos " => "Auxiliar en servicios farmaceuticos ",
"Auxiliar administrativo en salud" => "Auxiliar administrativo en salud",
"Atención integral a la primera infancia" => "Atención integral a la primera infancia",
"Auxiliar en enfermería" => "Auxiliar en enfermería",
"Asistente en comercio internacional" => "Asistente en comercio internacional",
"Asesor comercial " => "Asesor comercial ",
"Asistente de mercadeo" => "Asistente de mercadeo",
"Asistente de desarrollo de software " => "Asistente de desarrollo de software ",
"Asistente administrativo" => "Asistente administrativo"
        ];
        foreach ($data as $nombre => $descripcion) {
            TituloEducativo::create([
                'nombre' => $nombre,
                'descripcion' => $descripcion,
            ]);
        }
    }
}
