apiVersion: v1
kind: Secret
metadata:
  name: yosoy-secrets
  namespace: apps
type: Opaque
stringData:
  DB_PASSWORD: "Fk3:fTBt$=f`kh0P"
  AWS_ACCESS_KEY_ID: "AKIAUMFJASHM5XIIXDWK"
  AWS_SECRET_ACCESS_KEY: "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"
  MAIL_PASSWORD: "gsbkvruwvkiaunnh"
  RECAPTCHA_SECRET_KEY: "6Ld1fAsqAAAAANoHUsYRxSOvGlBq8CF4ATzWeEQ-"
  APP_KEY: "base64:fUs+diAQPs0eZo2Ufgihmh1tLFMmUp9cdP5SC12FymA="