apiVersion: v1
kind: Secret
metadata:
  name: yosoy-secrets
  namespace: apps
type: Opaque
stringData:
  DB_PASSWORD: "Fk3:fTBt$=f`kh0P"
  AWS_ACCESS_KEY_ID: "AKIAUMFJASHM5XIIXDWK"
  AWS_SECRET_ACCESS_KEY: "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"
  MAIL_PASSWORD: "gsbkvruwvkiaunnh"
  RECAPTCHA_SECRET_KEY: "6Ld1fAsqAAAAANoHUsYRxSOvGlBq8CF4ATzWeEQ-"
  APP_KEY: "base64:fUs+diAQPs0eZo2Ufgihmh1tLFMmUp9cdP5SC12FymA="
  PASSPORT_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDDpYdvYTzdf9zK       
    S1wVo8XFlREWfqak4wIcSEO5NzNlOSqSb1O24uUBdYWR5OHuuzZLpQEyjFVlOv1+       
    4NZFAxE/tg/HA7hDFxX7rSwNprn86DofEq5CaFkPDLdokBKmq6cPoYwg09cgMOgG       
    ACV3zg+9B9VN2ezhMDw7I4MTP8HrOe9mIAFcVSTsG/PqQitbxOwXQ//cGG/n3goF       
    lepIbfR7StB+KrLwDLutxueQHuMtOdJdRNkG/UOGvc1JeQFhNO/E84BuYRNoSoaw       
    Mmm79qGaNwhQkVCnG+GrwSdp+dNPFJoSQbLiGVrR89VaRsc1DpA63F1ouCFtg4Hf       
    mRQw24jXC6BzfRBZvVvdBGjzrFljiTGv7P+UpIdQm39J4O/GqnjA5mGa6YfDll9X       
    t8sdVRLmLqq3DGb9UVH0QhCf9IcZJVQvFNlWvKp2OSRauN2t3qjOhmfPZ7TRJXlA       
    wjqXmpFzHAN+mDot1xSZc2eLcn6wo2ggVPMgVC/2zCA/SFQTKt9PYcjgiYVUgjEr       
    TOw4H4MNlNI3oaONuCqCPMuTsXZqnmZLMd9Y23GD99X1yQCyuR3YdbS4sOPI2wIg       
    bIohianEPHOYOfR11BKCSrVWTPl51M+IEAtNaiqEhCMeM259XX3mtErTEdbbIrVz       
    rFTg/Uo0ewrYp0qvuK63GdSYJ05aVwIDAQABAoICADFE5i5uVl2RbZCkGbR5Yby4       
    JW18x4qOgGGO8T8bX54GH2pxDqvnx7PuXIy5DwyHqMyz6PFJ1deAW4YwKMWIWDer       
    KZ38mdKLZcXTflyRuBSwhrJ8idW/YW4gza9PWOMQJyoQjLFXp707k7KvJsBc7Cm2       
    Z0kLsFOlSgW6k6+tRrBuDpOxS6Zs6rdq8qnzr+eUV8AkJ7LNlKDXkb6GWlGTHxZN       
    aOPc7OL20eyZQodQv/ULsqY6SE0ySmcMNT5jcq2AH0GB8L3bRH/nBLQqfeYP3fJw       
    GW/wqFbs9o/CPKK7fzNTBNnEIcA+klh9ByWM3W3HFRs9k2hjtkdV7sbYTfVf072i       
    s603PQwDKYEt3mupD6k5A97AeNE9RBZAcHSBkvsEjaklVWFjIOOQYSCEwGHbQAYe       
    xme2eosMarPjCGLayKnURv0IgYVIXmDB+Kzvl3oy9rf4aohiquxrkbxASi7DFXOp       
    1v+N08Uzdu8Uq/CVC5VPBMjDuhIzEUGBXunk0sGJ0Pb2H4aNgJiSSdgpaHKQobqk       
    vl8FiGPnT3iiRaQ0/GE8E/qmIGlutjyyWQxYqZclNNVAWqPODMqnj/N/maN34Bpf       
    MeTM2WKStJ0v+2/Gp3srh/UHPfFtCcuzDikWmPvtfoMScoGIQOg+7vqnLVyI++6Y       
    cMIcApQze2qeTJ4h5QFBAoIBAQD2+1+ansJo5CXW27SH3QtPE6Wn7iIU6zvG+c8d       
    1LRftJqVZfcX2eVxFi582TwQzH7rueQ4yomF7OLJPFAA+ezFAeSdFldD6AJx2asq       
    bgJUOOLM2KR4LoTyuBZ4QZ4B40CFh87lvaJEk4oLHkg+Z6w1EmAqe6xHFh42XJIY       
    Qk1YzLgFJctEzCL4a0svyl5KeOlZIGDAJLdUy8vc7muIuqRbbjHWdftCbHZGYnjW       
    6dOSUV2nfULLJjPxUJ9tOkluzTdoAL1KRl5AV7zw8fsPb9Pjke2+RAuvO4VhA+nN       
    reE7G5UrKiWMKL/s53k3ef2QwX8E0C/jw71wWOLFT712l38NAoIBAQDKyk5pDCiD       
    aaA7FXmY9K13lmmBIouoOKE7KjIjKQXEHec7SjWeRSe2RoqM9IHoiuFiww6v1oDX       
    GCCFqyWWTfB82YenEBfDp2IHLStFZvS3d9EuyVqhS72kFA+T9IW82YZcPj1VnWHj       
    uD3C8y+U8MK/FfiekmnLxoKMkzr3SaOf5qajpADW6nzRFn8l7ulzb/g0W4mitueE       
    czA0dXC2MDMVGUBJ/ckTAaZwteWm7BAvq+4Bd8ygXUaq/KfYRIEX87hlkbEjFPj8       
    uSjM6PWzj1P+15daivAn9a+kxK2Pifh7Uc47e/J5W3QvnLCG2Rfwrw88aaZ0x9fB       
    05AtcS3au4XzAoIBAQDyqrmcqjBJ7yBeozAV7dGWuK8i+I70DsyFDB28Kamv/zuD       
    XtQQ0z7khe7XLHof500tP1BFnHrS45VQM7pHu0gvqVR+I91KE0OTqVLMNZqENgBh       
    VNsEWnC2KrmpHo+pOyfCC1X11QUCbBROKErDRgmle5CRLUJv9gNpVjsVKs/kWADW       
    zfOSfSA/BOyy4BsVAQgFUhK9t1WKM1LymC+AACJM01CUbweYlAkBzu77+nKuaNOk       
    JSbjg321tIlwQLy16VxvC4rw14LzpUE3XApZeH6wMkltkF4Kpmi+kaG/PQD3mnpO       
    FvMda0xn8GbhYzMIb5XlnMfw+fm/0RW+2EJHq0JhAoIBAQDGDYtC4RL4NUK+MZ0O       
    m3iHYSkta5XF93jQFcfduwTcou/gYfu31YaRaJeMTohJmsnA8Qv5A5/VcsTgh2Qw       
    RXJoHPN1YCw1c9YzeBPYtlKulKCB9zlCanyOMOF9+MRcyn2EvWydnxWpl5kKOwPv       
    jKxGf6jPBeO5luiNboWaWhsp4dRB4bzIKT853aTUYV8y1NouGHB1r/iwzOb5dPFd       
    nfll08GMAgZNP8FUNvJRch/kzx+l42DABhksiZFLkKwbvnYLDJ1Zy/PYruWAKs08       
    TvET5W72iNc/z515aHSxyWga2Kx4P/dyOrVggsGNEZ1l/TL+J5jgWQUJUhxvpSfJ       
    hnetAoIBAQCd61kw3AplSnxBJaBmzXyfDEY8L0McSVl2/BgwN/FI4dSJ+0+2VUVS       
    8/DkRdeXGrUS8/xmYhvkIXmNWLbyf/a47YVT+xF2HTOs9AoT3/jBr2HN9dRBrgug       
    dlYrE0lpW9UnIdj4DnIM2KmAYtryTCRBL4OsGqzLN/b+Td8nctpXIGAhJn1baS1w       
    C5ETDd+fTyNYvOH7m/XvlwWEjBommH4ieHvcdnSOImcRMZ3ZEJWFj6Mz+w2wyM/u       
    8KX49OO0+V++tajTi8jYFo6T/I/7azWDfLHD7MqrQKfsYyJM9CcdenIHBITnjdB7       
    FZBefzVQKIT75Je2oA3cO8ZQ4qIqVCub
    -----END PRIVATE KEY-----
  PASSPORT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAw6WHb2E83X/cyktcFaPF       
    xZURFn6mpOMCHEhDuTczZTkqkm9TtuLlAXWFkeTh7rs2S6UBMoxVZTr9fuDWRQMR       
    P7YPxwO4QxcV+60sDaa5/Og6HxKuQmhZDwy3aJASpqunD6GMINPXIDDoBgAld84P       
    vQfVTdns4TA8OyODEz/B6znvZiABXFUk7Bvz6kIrW8TsF0P/3Bhv594KBZXqSG30       
    e0rQfiqy8Ay7rcbnkB7jLTnSXUTZBv1Dhr3NSXkBYTTvxPOAbmETaEqGsDJpu/ah       
    mjcIUJFQpxvhq8EnafnTTxSaEkGy4hla0fPVWkbHNQ6QOtxdaLghbYOB35kUMNuI       
    1wugc30QWb1b3QRo86xZY4kxr+z/lKSHUJt/SeDvxqp4wOZhmumHw5ZfV7fLHVUS       
    5i6qtwxm/VFR9EIQn/SHGSVULxTZVryqdjkkWrjdrd6ozoZnz2e00SV5QMI6l5qR       
    cxwDfpg6LdcUmXNni3J+sKNoIFTzIFQv9swgP0hUEyrfT2HI4ImFVIIxK0zsOB+D       
    DZTSN6GjjbgqgjzLk7F2ap5mSzHfWNtxg/fV9ckAsrkd2HW0uLDjyNsCIGyKIYmp       
    xDxzmDn0ddQSgkq1Vkz5edTPiBALTWoqhIQjHjNufV195rRK0xHW2yK1c6xU4P1K       
    NHsK2KdKr7iutxnUmCdOWlcCAwEAAQ==
    -----END PUBLIC KEY-----
