apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: yosoyapp
  namespace: default
  labels:
    app: yosoyapp
spec:
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 75
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yosoyapp
