name: Production

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  APPLICATION: yosoyapp
  ECR_REPOSITORY: yosoyapp

jobs:
  deploy:
    name: Build and deploy on production
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags

    - name: Deploy to Amazon EKS cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        KUBECTL_VERSION: "v1.22.0"
        IAM_VERSION: "0.5.6"
      with:
        args: set image deployment/$APPLICATION $ECR_REPOSITORY=$ECR_REGISTRY/$ECR_REPOSITORY:$SHORT_SHA

    - name: Verify deployment
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "v1.22.0"
        IAM_VERSION: "0.5.6"
      with:
        args: rollout status deployment/$APPLICATION
